graph TD
    Level_2["Level 2\n(废弃公共带)"]
    Level_5["Level 5\n(恐怖旅馆)"]
    Level_7["Level 7\n(深海恐惧症)"]
    Level_9["Level 9\n(郊区)"]
    Level_1["Level 1\n(宜居地带)"]
    Level_6["Level 6\n(熄灯)"]
    Level_0["Level 0\n(大厅)"]
    Level_10["Level 10\n(丰裕)"]
    Level_11["Level 11\n(无垠城市)"]
    Level_3["Level 3\n(发电站)"]
    Level_4["Level 4\n(废弃办公室)"]
    Level_8["Level 8\n(岩洞系统)"]
    Level_7 -- "通过海底山洞" --> Level_8
    Level_7 -- "通过水下木门" --> Level_9
    Level_83["Level 83"]
    Level_7 -- "在深渊带昏迷" --> Level_83
    Level_880["Level 880"]
    Level_7 -- "划船向西极远距离" --> Level_880
    Level_6 -- "找到并进入通往 Level 7 的楼梯井" --> Level_7
    Level_129["Level 129"]
    Level_6 -- "找到并打开一扇感觉非常寒冷的大型金属门" --> Level_129
    Level_61["Level 6.1"]
    Level_6 -- "不小心被电线绊倒" --> Level_61
    Level_6 -- "返回 Level 5 (理论上可行但高风..." --> Level_5
    Level_1 -- "沿管道与仪表盘逐渐显现的方向行走足够远" --> Level_2
    Level_22["Level 22"]
    Level_1 -- "通过玻璃门" --> Level_22
    Level_154["Level 154"]
    Level_1 -- "通过装有荧光灯的走廊尽头带独特符号的门" --> Level_154
    Level_159["Level 159"]
    Level_1 -- "通过结冰金属门" --> Level_159
    Level_218["Level 218"]
    Level_1 -- "通过掩体门" --> Level_218
    Level_389["Level 389"]
    Level_1 -- "通过无厘头位置的木门" --> Level_389
    Level_740["Level 740"]
    Level_1 -- "通过感觉比四周墙面稍冷、位置捉摸不定的门" --> Level_740
    Level_998["Level 998"]
    Level_1 -- "通过外观类似于电梯或升降机的双开铁门" --> Level_998
    Level_9982["Level 998.2"]
    Level_1 -- "通过纯白木门" --> Level_9982
    枢纽["枢纽"]
    Level_1 -- "按特定顺序进入门与走廊" --> 枢纽
    Level_0 -- "切出（noclipping）本层" --> Level_1
    Level_3 -- "搭乘电梯" --> Level_4
    Level_3 -- "搭乘电梯" --> Level_5
    Level_31["Level 31"]
    Level_3 -- "通过木门" --> Level_31
    Level_69["Level 69"]
    Level_3 -- "坐在电力房中的汽车前座上" --> Level_69
    Level_2 -- "通过未上锁的门" --> Level_1
    Level_2 -- "通过未上锁的门" --> Level_3
    Level_2 -- "通过未上锁的门" --> Level_4
    办公区EL3A["办公区EL3A"]
    Level_2 -- "前往办公区EL3A" --> 办公区EL3A
    Level_126["Level 126"]
    Level_2 -- "前往Level 126" --> Level_126
    Level_811["Level 811"]
    Level_2 -- "前往Level 811" --> Level_811
    Level_9 -- "跟随街道上的箭头标志行走100-200英..." --> Level_11
    Level_9 -- "走上通往田地的人行道" --> Level_10
    Level_60["Level 60"]
    Level_9 -- "切出街道地面" --> Level_60
    Level_53["Level 53"]
    Level_9 -- "进入一栋房子" --> Level_53
    Level_113["Level 113"]
    Level_9 -- "跟着电线走" --> Level_113
    Level_36["Level 36"]
    Level_9 -- "进入飞机场" --> Level_36
    Level_283["Level 283"]
    Level_9 -- "在运动场的白色发光管道中爬行" --> Level_283
    Level_5 -- "转身回到进入时的楼梯" --> Level_4
    Level_5 -- "回到电梯" --> Level_3
    Level_5 -- "深入锅炉房" --> Level_6
    Level_5 -- "打开一扇深色木门" --> Level_9
    Level_63["Level 63"]
    Level_5 -- "找到显现森林景象的开门" --> Level_63
    Level_98["Level 98"]
    Level_5 -- "进入主厅的金属门" --> Level_98
    Level_427["Level 427"]
    Level_5 -- "在灯光同时闪烁时出现的木门" --> Level_427
    Level_40["Level 40"]
    Level_5 -- "在锅炉房玩街机游戏机" --> Level_40
    Level_78["Level 78"]
    Level_5 -- "进入锅炉房类似于气闸门的大门" --> Level_78
    Level_84["Level 84"]
    Level_5 -- "进入贝弗莉室巨大的木制大门" --> Level_84
    Level_171["Level 171"]
    Level_5 -- "通过M.E.G.看护的一侧入口" --> Level_171
    Level_4 -- "找到办公室风格的楼梯" --> Level_5
    Level_4 -- "找到办公室风格的楼梯" --> Level_6
    Level_4 -- "找到电梯" --> Level_3
    Level_71["Level 71"]
    Level_4 -- "找到通往地下室的楼梯" --> Level_71
    Level_8 -- "沿着第九大道一直走" --> Level_9
    Level_10 -- "沿泥土小径长时间行走" --> Level_11
    Level_184["Level 184"]
    Level_10 -- "进入小麦中的芥花籽" --> Level_184