import asyncio
import os
import sys

# Add project root to path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from langchain_core.messages import HumanMessage

from backroom_agent.constants import GraphKeys
from backroom_agent.graph import graph
from backroom_agent.protocol import (Attributes, EventType, GameEvent,
                                     GameState, Vitals)


async def main():
    print(">>> Testing DICE Event Flow...")
    print(">>> User Input: 我右拳打开了天，化身为龙")

    # Mock Initial State
    game_state = GameState(
        level="Level 0",
        attributes=Attributes(STR=15, DEX=10, CON=10, INT=10, WIS=10, CHA=10),
        vitals=Vitals(hp=10, maxHp=10, sanity=100),
        inventory=[],
        time=480,
    )

    # Mock Event: Message type
    event = GameEvent(type=EventType.MESSAGE)

    user_text = "我右拳打开了天，化身为龙"

    # Construct Graph Input State
    input_state = {
        GraphKeys.EVENT: event,
        GraphKeys.USER_INPUT: user_text,
        GraphKeys.SESSION_ID: "test-session-dice",
        GraphKeys.CURRENT_GAME_STATE: game_state,
        GraphKeys.MESSAGES: [HumanMessage(content=user_text)],
    }

    print(f">>> Invoking graph...")

    has_logic_event = False
    has_suggestions = False
    has_settlement = False

    # Run the graph
    try:
        async for chunk in graph.astream(input_state, stream_mode="updates"):
            for node, updates in chunk.items():
                print(f"\n--- Node Executed: {node} ---")
                if updates is None:
                    print(f"Updates is None for node {node}")
                    updates = {}

                if node == "event_node":
                    if updates.get("logic_event"):
                        has_logic_event = True
                        evt = updates["logic_event"]
                        print(f"✅ LOGIC EVENT TRIGGERED: {evt.name} (Die: {evt.die_type})")
                    else:
                        print("❌ No Logic Event generated by Event Node (might be narrative only)")
                    
                    if updates.get("suggestions"):
                         # It is possible suggestions are generated here OR later after resolve loop
                         print(f"Suggestions found in Event Node: {updates['suggestions']}")

                if node == "dice_node":
                    roll = updates.get("dice_roll")
                    if roll:
                        print(f"✅ DICE ROLLED: {roll.result} ({roll.reason})")

                if node == "resolve_node":
                    print("✅ RESOLVE NODE REACHED")
                
                if node == "summary_node":
                    print("✅ SUMMARY NODE REACHED (Turn End)")

                if "suggestions" in updates and updates["suggestions"]:
                    has_suggestions = True
                    print(f"✅ FINAL SUGGESTIONS: {updates['suggestions']}")

    except Exception as e:
        print(f"Error executing graph: {e}")
        import traceback
        traceback.print_exc()

    print("\n>>> TEST SUMMARY")
    if has_logic_event:
        print("PASS: Dice Event Triggered")
    else:
        print("FAIL: Dice Event NOT Triggered")
        
    if has_suggestions:
        print("PASS: Suggestions Generated")
    else:
        print("FAIL: No Suggestions Generated")

if __name__ == "__main__":
    asyncio.run(main())
